services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payments
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d payments"]
      interval: 2s
      timeout: 2s
      retries: 30

  wiremock:
    image: wiremock/wiremock:3.9.2
    ports:
      - "8091:8080"
    command: ["--global-response-templating", "--disable-gzip"]

  localstack:
    image: localstack/localstack:3.7
    environment:
      SERVICES: sqs
      AWS_DEFAULT_REGION: us-east-1
    ports:
      - "4567:4566"
